spring:
  application:
   name: experimental
   sql:
     init:
       mode: always

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    jdbc-url: ${DB_URL}
    jdbcUrl: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
  mongodb:
    uri: ${MONGO_URL}
apps:
  source:
    file-path: ${FILE_PATH}
    collection-mongo: ${MONGO_COLLECTION}